version: "3.8"
name: "cinema-plus-be"
services:
  mongo-express:
    image: mongo-express
    restart: always
    env_file: ./.env
    ports:
      - ${ME_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}?authSource=admin
      ME_CONFIG_MONGODB_SERVER: mongodb
  mongodb:
    container_name: cinema-plus-mongodb
    image: mongo:6.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - db:/data/db
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512m
  app:
    container_name: cinema-plus-api
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - .:/usr/src/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - DB_HOST=mongodb
      - DB_USER=${MONGODB_USER}
      - DB_PASSWORD=${MONGODB_PASSWORD}
      - DB_NAME=${MONGODB_DATABASE}
      - DB_PORT=${MONGODB_PORT}
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512M
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    env_file: ./.env
    networks:
      prometheus_grafana:
        aliases:
          - prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ${PATH_TO_YOUR_PROMETHEUS}/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    env_file: ./.env
    networks:
      prometheus_grafana:
        aliases:
          - grafana
    ports:
      - ${GRAFANA_PORT}:3000
    restart: unless-stopped

networks:
  prometheus_grafana:
    driver: bridge

volumes:
  db:
